// Apple Music storefront codes for "Additional countries": discovery.countries
// entries must come from this map, and the editor uses it for display names
// and its picker. Every code verified live 2026-07-19 (both the most-played
// feed and the purchase RSS respond; kr/cn purchase feeds are nearly empty but
// harmless). Covers the P1–P3 tiers plus same-language storefronts.
export const STOREFRONTS = {
  ar: 'Argentina',
  bo: 'Bolivia',
  br: 'Brazil',
  cl: 'Chile',
  cn: 'China',
  co: 'Colombia',
  cr: 'Costa Rica',
  do: 'Dominican Republic',
  ec: 'Ecuador',
  es: 'Spain',
  gt: 'Guatemala',
  hk: 'Hong Kong',
  hn: 'Honduras',
  id: 'Indonesia',
  in: 'India',
  jp: 'Japan',
  kr: 'Korea',
  mo: 'Macau',
  mx: 'Mexico',
  my: 'Malaysia',
  ng: 'Nigeria',
  ni: 'Nicaragua',
  pa: 'Panama',
  pe: 'Peru',
  ph: 'Philippines',
  py: 'Paraguay',
  sg: 'Singapore',
  sv: 'El Salvador',
  th: 'Thailand',
  tw: 'Taiwan',
  uy: 'Uruguay',
  ve: 'Venezuela',
  vn: 'Vietnam',
  za: 'South Africa',
}
